# Generated by Django 2.2.5 on 2019-09-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=150)),
                ('c_id', models.CharField(max_length=100)),
                ('c_phone', models.CharField(max_length=14)),
                ('c_email', models.CharField(max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('te_name', models.CharField(max_length=150)),
                ('te_id', models.CharField(max_length=100)),
                ('te_phone', models.CharField(max_length=14)),
                ('te_email', models.CharField(max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('t_opened', models.DateTimeField(auto_now_add=True)),
                ('t_subject', models.CharField(max_length=100)),
                ('t_body', models.TextField()),
                ('c_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Customer')),
                ('t_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Category')),
                ('t_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Status')),
                ('tech_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Technician')),
            ],
        ),
    ]
