# Generated by Django 2.2.5 on 2019-09-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='t_closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date closed'),
        ),
    ]
