# Generated by Django 2.2.5 on 2020-01-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20200116_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultticket',
            old_name='body',
            new_name='ticket_body',
        ),
        migrations.AlterField(
            model_name='laptopcheckout',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Reason'),
        ),
    ]
