# Generated by Django 3.0.2 on 2020-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20200123_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsetup',
            name='t_body',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information (If Any)'),
        ),
    ]
