# Generated by Django 3.0.2 on 2020-03-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_equipmentsetup_t_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopcheckout',
            name='l_body',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information (If Any)'),
        ),
    ]
