# Generated by Django 2.2.5 on 2019-09-24 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_auto_20190924_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tech_info',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='c_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
