# Generated by Django 3.0.2 on 2020-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_laptopcheckout_l_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='printers',
            name='p_body',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information (If Any)'),
        ),
    ]
