# Generated by Django 3.0.2 on 2020-03-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_printers_p_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstaff',
            name='ns_body',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information (If Any)'),
        ),
    ]
