# Generated by Django 2.2.5 on 2019-09-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_auto_20190924_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='t_assigned',
            field=models.CharField(default='test', max_length=150, verbose_name='Assigned To'),
            preserve_default=False,
        ),
    ]
