# Generated by Django 2.2.5 on 2019-09-25 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ticketing", "0007_ticket_t_assigned")]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="c_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer Name",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="t_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ticketing.Category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="t_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ticketing.Status",
                verbose_name="Status",
            ),
        ),
    ]
