# Generated by Django 3.0.2 on 2020-03-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_training_tr_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='pr_body',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information (If Any)'),
        ),
    ]
