# Generated by Django 2.2.5 on 2019-09-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ticketing", "0009_auto_20190925_1505")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="u_sort_type",
            field=models.CharField(
                default="-pk", max_length=30, verbose_name="Sort By Value"
            ),
            preserve_default=False,
        )
    ]
