# Generated by Django 2.2.5 on 2019-09-30 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ticketing", "0011_auto_20190927_1033")]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="c_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer Name",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="t_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Technician",
            ),
        ),
    ]
