# Generated by Django 2.2.5 on 2019-10-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ticketing", "0015_customuser_u_filter_type")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="force_change",
            field=models.BooleanField(
                default=True, verbose_name="Force Password Change on Next Login"
            ),
        )
    ]
