# Generated by Django 2.2.5 on 2019-11-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0016_customuser_force_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='days_opened',
            field=models.TextField(blank=True, null=True, verbose_name='Number of Days Open'),
        ),
    ]
