# Generated by Django 2.2.5 on 2019-11-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0021_auto_20191113_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Event')),
                ('start_time', models.TimeField(verbose_name='Time of Event')),
                ('end_time', models.TimeField(verbose_name='Approx End of Event')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Rooms')),
            ],
        ),
    ]
