# Generated by Django 2.2.5 on 2019-12-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0022_equipmentsetup_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsetup',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketing.Ticket'),
            preserve_default=False,
        ),
    ]
