# Generated by Django 2.2.5 on 2019-12-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0023_equipmentsetup_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsetup',
            name='date',
            field=models.TextField(verbose_name='Date of Event'),
        ),
        migrations.AlterField(
            model_name='equipmentsetup',
            name='end_time',
            field=models.TextField(verbose_name='Approx End of Event'),
        ),
        migrations.AlterField(
            model_name='equipmentsetup',
            name='start_time',
            field=models.TextField(verbose_name='Time of Event'),
        ),
    ]
